library(proxy)
library(stringi)
library(tm)
library(SnowballC)
library(tm.plugin.mail)
setwd("~/Downloads/MISC/untitled folder 2/20news-bydate/20news-bydate-train")
options(stringsAsFactors = FALSE)
path <- "~/Downloads/MISC/untitled folder 2/20news-bydate/20news-bydate-train/"
files <- c("rec.motorcycles", "rec.sport.baseball", "talk.politics.guns")
baseball <- Corpus(DirSource(files),readerControl=list(reader=readPlain))
#baseball <- tm_map(baseball, PlainTextDocument, quote = FALSE)
baseball <- tm_map(baseball, content_transformer(tolower))
baseball <- tm_map(baseball, removeWords, stopwords("english"))
baseball <- tm_map(baseball, content_transformer(removePunctuation))
baseball <- tm_map(baseball, content_transformer(stripWhitespace))
baseball <- tm_map(baseball, content_transformer(removeNumbers))
baseball <- tm_map(baseball, content_transformer(stemDocument))
#baseball <- tm_map(baseball, stemCompletion, dictionary=dictCorpus)
#baseball <- tm_map(baseball, PlainTextDocument, quote = FALSE)
# baseball <- tm_map(baseball, removeSignature)
head(baseball[1])
dtm <- DocumentTermMatrix(baseball, control=list(weighting=weightTfIdf, minWordLength=2, termFreq=5))
dtm <- removeSparseTerms(dtm, 0.99)
dtm
inspect(dtm[1:5, 1:5])
dim(dtm)
freq <- colSums(as.matrix(dtm))
length(freq)
df <- as.data.frame(inspect(dtm))
