library(proxy)
library(stringi)
library(tm)
library(SnowballC)
wiki <- "https://en.wikipedia.org/wiki/Michael_Jackson"
# music <- c("michael_Jackson", "The_Beatles", "Elvis_Presley", "Elton_John")
# article <- character(length(music))
# for (i in 1:length(music)) {
#   article[i] <- stri_flatten(readLines(stri_paste(wiki, music[i])), col = " ")
# }
article <- readLines(wiki)
article <- paste(article, collapse = " ")
docs <- Corpus(VectorSource(article))
docs <- tm_map(docs, function(x) stri_replace_all_regex(x, "<.+?>", " "))
docs <- tm_map(docs, function(x) stri_replace_all_fixed(x, "\t", " ")) 
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, tolower)
docs <- tm_map(docs, PlainTextDocument)
docs <- tm_map(docs, removeWords, stopwords("english"))
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, stemDocument)
docs <- tm_map(docs, stripWhitespace)
docs <- tm_map(docs, function(x) stri_replace_all_regex(x, "jacksons", "jackson"))
docs <- tm_map(docs, function(x) stri_replace_all_regex(x, "jackson", ""))
docs <- tm_map(docs, function(x) stri_replace_all_regex(x, "michael", ""))
docs <- tm_map(docs, function(x) stri_replace_all_regex(x, "may", ""))
docs <- tm_map(docs, PlainTextDocument)
head(docs[[1]])
dtm <- DocumentTermMatrix(docs)
dtm 
inspect(dtm[1, 1:20])
freq <- colSums(as.matrix(dtm))
length(freq)
# ord <- order(freq)
# freq[head(ord)]  
# freq[tail(ord)]
freq <- sort(colSums(as.matrix(dtm)), decreasing=TRUE)
head(freq, 14)
library(wordcloud)
set.seed(123456)
wordcloud(names(freq), freq, min.freq=20)
wordcloud(names(freq), freq, min.freq=20, scale=c(5, .1), colors=brewer.pal(6, "Dark2"))
library(cluster)
d <- dist((dtm), method="euclidean")
